version: '3.8'

services:  # <--- ¡ESTA LÍNEA ES CLAVE! Todo lo demás debe ir un paso hacia adentro

  db:      # Dos espacios de sangría
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: devops_db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: super_secret_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  flask_app: # Al mismo nivel que 'db', dentro de 'services'
    build: .
    container_name: flask_server
    ports:
      - "5000:5000"
    environment:
      - APP_NAME=Mi_App_DevOps
      - APP_VERSION=1.0.0
      - DB_HOST=db
      - DB_NAME=devops_db
      - DB_USER=admin_user
      - DB_PASSWORD=super_secret_password
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "8888:80"  # <--- Cambiamos el de la izquierda (el de tu PC)
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    depends_on:
      - db

volumes:   # Al nivel raíz (borde izquierdo), igual que 'services'
  postgres_data: