name: flask app hola

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

# Definimos la versión aquí arriba para que la cambies fácilmente a 2.0.0 después
env:
  APP_VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Login hacia GitHub Container Registry
        # Usamos GITHUB_TOKEN nativo para evitar configurar secretos manuales
        run: echo "${{ secrets.GT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Construir imagen de docker
        # Construimos la imagen dos veces: una con el tag de la versión y otra con 'latest'
        run: |
          docker build -t ghcr.io/isaacyav97/docpost:${{ env.APP_VERSION }} .
          docker build -t ghcr.io/isaacyav97/docpost:latest .

      - name: Publicar la imagen
        # Subimos ambos tags a GHCR como pide el examen
        run: |
          docker push ghcr.io/isaacyav97/docpost:${{ env.APP_VERSION }}
          docker push ghcr.io/isaacyav97/docpost:latest